### ISSUE TITLE
async/await

### ISSUE THREAD

**Issue by panpapryk** [mattpolzin/VaporOpenAPI#12]
Hi, 
Is there any plan to release version that is compatible with new async/await approach instead EventLoopFuture?

**Comment by mattpolzin** [comment]
No plans, no. However, I’d gladly accept pull requests that modernized this library. It was always meant to be more of a prototype showing how OpenAPIKit could be integrated with from other frameworks like Vapor, though I did end up using this library myself on at least one project a while ago.

**Comment by mattpolzin** [comment]
Closed by https://github.com/mattpolzin/VaporOpenAPI/pull/13
