### ISSUE TITLE
How can I configure stable Dictionary in Response by selecting JSONEncoder vs e.g. FineJSON ?

### ISSUE THREAD

**Issue by astrotuna201** [mattpolzin/VaporOpenAPI#17]
Many thanks for your nice libraries!

In OpenAPIKit it is mentioned one can obtain ordered json samples by using FineJSON or Yams ... 
Is it possible to configure this in VaporOpenAPI, and if so, how?

I tried it in the AsyncResponseEncodable -> encodeResponse extension function, but to no avail ...

**Comment by mattpolzin** [comment]
If you'd like to use a different encoder (e.g. one that supports stable ordering), there are two places you need to consider plugging into OpenAPI generation.

First, `VaporOpenAPI` uses an encoder in certain situations to get information about how Swift structures will be represented in responses, so you can tell it what encoder to use for those purposes. An example of this can be seen in the VaporOpenAPIExample, though this example simply plugs the default JSON encoder in after setting it up to sort keys alphanumerically (you may want to use an entirely different encoder to get order stability):
https://github.com/mattpolzin/VaporOpenAPIExample/blob/main/Sources/App/Controllers/APIDocsController.swift#L80

At that point you've got what you need to create an OpenAPI Document that preserves order, but then you probably want to encode _that OpenAPI document_ as JSON or YAML and that's the second place where you can plug in your own choice of an encoder. In the aforementioned example, the Yams encoder is used (which does have order-stability) but you could also use some alternative JSON encoder:
https://github.com/mattpolzin/VaporOpenAPIExample/blob/main/Sources/App/Controllers/APIDocsController.swift#L93

**Comment by astrotuna201** [comment]
Ah, many thanks! Just to clarify: Since the JSONEncoder Type is hard-coded into much of the current VaporOpenAPI structure, this means I would have to re-implement those, for example using FineJSONEncoder, right? I guess a more generic way might be to change this to Vapor's ContentEncoder ...

**Comment by mattpolzin** [comment]
> Since the JSONEncoder Type is hard-coded into much of the current VaporOpenAPI structure

Sigh. I didn't realize that when answering your question, but of course you are right. The encoder it accepts is not generic, it just allows you to plug in a different instantiation of the Foundation encoder.

That means that to get full order-stability throughout, you would need to change all of that piping of encoders around like you were suggesting.

However, if you have not tried it already, I would at least try using a different encoder for writing your OpenAPI document out. I think it is possible that the locations where you want to retain order are covered without changing the JSON encoder that is used to infer additional information. There's another totally separate thing that might cause problems here: I am not confident that all of the structures between definitions within Vapor and the transformations done by VaporOpenAPI are order-stable -- if anything passes through a regular `Dictionary` then we lose order stability without even leaving Swift.

**Comment by astrotuna201** [comment]
ok, thanks! That's what I thought ... Will see if I really need ordered stability ...
Cheers!
