### ISSUE TITLE
Response doesn't show for responses without a body

### ISSUE THREAD

**Issue by JaapWijnen** [mattpolzin/VaporOpenAPI#9]
I can't get the library to show in the docs what responses to expect from something like a delete request that would just return a `.noContent` header. Any tips on how to get that to display in the responses part of the docs?

I tried using the following context: 
```
struct DeleteContext: RouteContext {
    typealias RequestBodyType = EmptyRequestBody

    static let defaultContentType: HTTPMediaType? = nil
    static let shared = Self()

    let success: ResponseContext<HTTPStatus> = .init { response in
        response.status = .noContent
    }
}
```

**Comment by mattpolzin** [comment]
There was definitely a bug here! I've fixed it with version `0.0.17` of the library. Now HTTP status 204 (No Content) will not be skipped over when generating OpenAPI Response documentation.

I've also added an example that you can refer to here if that ends up being of any additional help: https://github.com/mattpolzin/VaporOpenAPIExample/blob/main/Sources/App/Controllers/HelloWorldController.swift#L35...L43 (along with the `DeleteContext` farther down in the same file).

If this doesn't solve your use-case or you have any other questions, feel free to reopen the ticket.

Thanks!
